server:
  port: 8080

zuul:
  routes:
    user-service:
      path: /users/**
      url: http://localhost:8081

    product-service:
      path: /products/**
      url: http://localhost:8082

      order-service:
        path:/order/**
        url:http://localhost:8083

